/**
 * Rules
 * The filter works as a series of rules so that each word can be mapped to a rule.  So \"Happy\" can become \"happy\" and \"b4d\" and become \"bad\".    With this API you can manage your rules. 
 *
 * OpenAPI spec version: 2.0.3
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * What kind of flag is it  You must have ENABLED if you want it to be active, without it it is a disabled rule  Everything from DICT and below is being deprecated 
 */
export type Flag = 'ENABLED' | 'DELETED' | 'COMMON' | 'WATCH' | 'SKIP' | 'PHRASE_RULE' | 'USERNAME' | 'FIRST_NAME' | 'LAST_NAME' | 'CITY' | 'STATE' | 'COUNTRY' | 'EMAIL_ADDRESS' | 'DICT' | 'OBJ' | 'GENERATED' | 'MODERATED' | 'WORD' | 'NOUN' | 'VERB' | 'PRONOUN' | 'ADJECTIVE' | 'ADVERB' | 'CONJ' | 'DET' | 'INTER' | 'PROPER_NOUN' | 'BIGRAM' | 'NGRAM' | 'SIMPLIFIED';

export const Flag = {
    ENABLED: 'ENABLED' as Flag,
    DELETED: 'DELETED' as Flag,
    COMMON: 'COMMON' as Flag,
    WATCH: 'WATCH' as Flag,
    SKIP: 'SKIP' as Flag,
    PHRASERULE: 'PHRASE_RULE' as Flag,
    USERNAME: 'USERNAME' as Flag,
    FIRSTNAME: 'FIRST_NAME' as Flag,
    LASTNAME: 'LAST_NAME' as Flag,
    CITY: 'CITY' as Flag,
    STATE: 'STATE' as Flag,
    COUNTRY: 'COUNTRY' as Flag,
    EMAILADDRESS: 'EMAIL_ADDRESS' as Flag,
    DICT: 'DICT' as Flag,
    OBJ: 'OBJ' as Flag,
    GENERATED: 'GENERATED' as Flag,
    MODERATED: 'MODERATED' as Flag,
    WORD: 'WORD' as Flag,
    NOUN: 'NOUN' as Flag,
    VERB: 'VERB' as Flag,
    PRONOUN: 'PRONOUN' as Flag,
    ADJECTIVE: 'ADJECTIVE' as Flag,
    ADVERB: 'ADVERB' as Flag,
    CONJ: 'CONJ' as Flag,
    DET: 'DET' as Flag,
    INTER: 'INTER' as Flag,
    PROPERNOUN: 'PROPER_NOUN' as Flag,
    BIGRAM: 'BIGRAM' as Flag,
    NGRAM: 'NGRAM' as Flag,
    SIMPLIFIED: 'SIMPLIFIED' as Flag
};