/**
 * Shared Components
 * Used to share components between specification docs
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * (Optional) The unique if for the client you want to update.  If empty it will set it to the client in your API key however if you are on Enterprise or Enterprise Site Licence you can have a sandbox or subClients.  A sandbox is an  environment where you can test the rules and you can use this to push data to your sandbox.  A subclient is another install of CommunitySift that allows you to have different rules, triggers, policies, queues but inherit the defaults from your  parent organization.  This allows you to have consistently.  So in the subclient case you can push items to queues to any of the clientIds you control 
 */
export type ClientIdOptional = number;