/**
 * Shared Components
 * Used to share components between specification docs
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The unique identifier for the moderator who has this checkout.  Note the checkout may be historic so check the expires date.
 */
export type ModeratorId = string;