/**
 * Shared Components
 * Used to share components between specification docs
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * We allow for multiple moderators to review the same item so we can cross validate important decisions.  If this value is 0 then it means it is done (which would be same as status == DONE) 
 */
export type ReviewsNeeded = number;