# Project default config values

### IMPORTANT ###################################################
#                                                               #
# THIS FILE IS TRACKED IN GIT                                   #
# NEVER PUT REAL API KEYS IN THIS FILE                          #
# INSTEAD, CREATE AND USE development.yaml                      #
# TO OVERRIDE THESE VALUES FOR YOUR OWN DEV ENVIRONMENT         #
#                                                               #
#################################################################

dev:
  # To replace this key for your dev environment,
  # create or update development.yaml with this same config tree
  # and place your key there.
  # DO NOT PLACE YOUR API KEY HERE, OR COMMIT development.yaml TO GIT
  # If you are bypassing SSO, you will need these environment variables to be set:
  #   NODE_ENV = development
  #   DISABLE_SSO = true
  apiKey: DEFAULT_DO_NOT_CHANGE_ME

port: 4200

contentSecurityPolicy: >
  default-src 'self';
  script-src 'self' 'unsafe-eval' sentry.io;
  style-src 'self' 'unsafe-inline' fonts.googleapis.com;
  img-src 'self' data;
  font-src 'self' fonts.gstatic.com;
  connect-src 'self' sentry.io;
  media-src 'none';
  object-src 'none';
  prefetch-src 'self' fonts.googleapis.com fonts.gstatic.com;
  child-src 'none';
  frame-src 'none';
  frame-ancestors 'none';
  upgrade-insecure-requests;
  block-all-mixed-content;
  report-uri https://o56381.ingest.sentry.io/api/1788710/security/?sentry_key=1f168fd1b0fa4b6999f1a901c0804a91&sentry_environment=${ENVIRONMENT}

db:
  redis:
    host: localhost
    port: 6381 # See docker-compose.debug.yml
    password: ''

session:
  secret: DEFAULT_DO_NOT_CHANGE_ME

sift:
  contentLogsApi:
    url: https://api.contentlogs.euon.aks.twohat.io
  inboxApi:
    url: https://api.rules-audit.euon.aks.twohat.io
  rulesApi:
    url: https://api.rules.euon.aks.twohat.io

sso:
  audience: sso.twohat.io
  issuer: localhost:4200
  loginUrl: https://sso.twohat.io/api/v1/login
  logoutUrl: https://sso.twohat.io/api/v1/logout
  validateUrl: https://sso.twohat.io/api/v1/validate/session
  privateUrl: https://sso.twohat.io
  signingKey: DEFAULT_DO_NOT_CHANGE_ME